<?php
/**
 * DashboardElementTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Looker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Looker;

/**
 * DashboardElementTest Class Doc Comment
 *
 * @category    Class */
// * @description DashboardElement
/**
 * @package     Looker
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DashboardElementTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DashboardElement"
     */
    public function testDashboardElement()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "dashboard_id"
     */
    public function testPropertyDashboardId()
    {
    }

    /**
     * Test attribute "look_id"
     */
    public function testPropertyLookId()
    {
    }

    /**
     * Test attribute "query_id"
     */
    public function testPropertyQueryId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "listen"
     */
    public function testPropertyListen()
    {
    }

    /**
     * Test attribute "refresh_interval"
     */
    public function testPropertyRefreshInterval()
    {
    }

    /**
     * Test attribute "refresh_interval_to_i"
     */
    public function testPropertyRefreshIntervalToI()
    {
    }

    /**
     * Test attribute "note_text"
     */
    public function testPropertyNoteText()
    {
    }

    /**
     * Test attribute "note_text_as_html"
     */
    public function testPropertyNoteTextAsHtml()
    {
    }

    /**
     * Test attribute "note_display"
     */
    public function testPropertyNoteDisplay()
    {
    }

    /**
     * Test attribute "note_state"
     */
    public function testPropertyNoteState()
    {
    }

    /**
     * Test attribute "title_hidden"
     */
    public function testPropertyTitleHidden()
    {
    }

    /**
     * Test attribute "title_text"
     */
    public function testPropertyTitleText()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "subtitle_text"
     */
    public function testPropertySubtitleText()
    {
    }

    /**
     * Test attribute "body_text"
     */
    public function testPropertyBodyText()
    {
    }

    /**
     * Test attribute "body_text_as_html"
     */
    public function testPropertyBodyTextAsHtml()
    {
    }

    /**
     * Test attribute "look"
     */
    public function testPropertyLook()
    {
    }

    /**
     * Test attribute "query"
     */
    public function testPropertyQuery()
    {
    }

    /**
     * Test attribute "edit_uri"
     */
    public function testPropertyEditUri()
    {
    }

    /**
     * Test attribute "merge_result_id"
     */
    public function testPropertyMergeResultId()
    {
    }

    /**
     * Test attribute "result_maker_id"
     */
    public function testPropertyResultMakerId()
    {
    }

    /**
     * Test attribute "result_maker"
     */
    public function testPropertyResultMaker()
    {
    }

    /**
     * Test attribute "can"
     */
    public function testPropertyCan()
    {
    }
}
