<?php
/**
 * DashboardFilterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DashboardFilterTest Class Doc Comment
 *
 * @category    Class */
// * @description DashboardFilter
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DashboardFilterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DashboardFilter"
     */
    public function testDashboardFilter()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "dashboard_id"
     */
    public function testPropertyDashboardId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "default_value"
     */
    public function testPropertyDefaultValue()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "explore"
     */
    public function testPropertyExplore()
    {
    }

    /**
     * Test attribute "dimension"
     */
    public function testPropertyDimension()
    {
    }

    /**
     * Test attribute "field"
     */
    public function testPropertyField()
    {
    }

    /**
     * Test attribute "row"
     */
    public function testPropertyRow()
    {
    }

    /**
     * Test attribute "listens_to_filters"
     */
    public function testPropertyListensToFilters()
    {
    }

    /**
     * Test attribute "allow_multiple_values"
     */
    public function testPropertyAllowMultipleValues()
    {
    }

    /**
     * Test attribute "required"
     */
    public function testPropertyRequired()
    {
    }

    /**
     * Test attribute "can"
     */
    public function testPropertyCan()
    {
    }
}
