<?php
/**
 * DBConnectionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DBConnectionTest Class Doc Comment
 *
 * @category    Class */
// * @description DBConnection
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DBConnectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DBConnection"
     */
    public function testDBConnection()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "dialect"
     */
    public function testPropertyDialect()
    {
    }

    /**
     * Test attribute "snippets"
     */
    public function testPropertySnippets()
    {
    }

    /**
     * Test attribute "host"
     */
    public function testPropertyHost()
    {
    }

    /**
     * Test attribute "port"
     */
    public function testPropertyPort()
    {
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "certificate"
     */
    public function testPropertyCertificate()
    {
    }

    /**
     * Test attribute "file_type"
     */
    public function testPropertyFileType()
    {
    }

    /**
     * Test attribute "database"
     */
    public function testPropertyDatabase()
    {
    }

    /**
     * Test attribute "db_timezone"
     */
    public function testPropertyDbTimezone()
    {
    }

    /**
     * Test attribute "query_timezone"
     */
    public function testPropertyQueryTimezone()
    {
    }

    /**
     * Test attribute "schema"
     */
    public function testPropertySchema()
    {
    }

    /**
     * Test attribute "max_connections"
     */
    public function testPropertyMaxConnections()
    {
    }

    /**
     * Test attribute "max_billing_gigabytes"
     */
    public function testPropertyMaxBillingGigabytes()
    {
    }

    /**
     * Test attribute "ssl"
     */
    public function testPropertySsl()
    {
    }

    /**
     * Test attribute "verify_ssl"
     */
    public function testPropertyVerifySsl()
    {
    }

    /**
     * Test attribute "tmp_db_name"
     */
    public function testPropertyTmpDbName()
    {
    }

    /**
     * Test attribute "jdbc_additional_params"
     */
    public function testPropertyJdbcAdditionalParams()
    {
    }

    /**
     * Test attribute "pool_timeout"
     */
    public function testPropertyPoolTimeout()
    {
    }

    /**
     * Test attribute "dialect_name"
     */
    public function testPropertyDialectName()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "example"
     */
    public function testPropertyExample()
    {
    }

    /**
     * Test attribute "user_db_credentials"
     */
    public function testPropertyUserDbCredentials()
    {
    }

    /**
     * Test attribute "user_attribute_fields"
     */
    public function testPropertyUserAttributeFields()
    {
    }

    /**
     * Test attribute "maintenance_cron"
     */
    public function testPropertyMaintenanceCron()
    {
    }

    /**
     * Test attribute "last_regen_at"
     */
    public function testPropertyLastRegenAt()
    {
    }

    /**
     * Test attribute "last_reap_at"
     */
    public function testPropertyLastReapAt()
    {
    }

    /**
     * Test attribute "sql_runner_precache_tables"
     */
    public function testPropertySqlRunnerPrecacheTables()
    {
    }

    /**
     * Test attribute "after_connect_statements"
     */
    public function testPropertyAfterConnectStatements()
    {
    }

    /**
     * Test attribute "pdt_context_override"
     */
    public function testPropertyPdtContextOverride()
    {
    }

    /**
     * Test attribute "can"
     */
    public function testPropertyCan()
    {
    }
}
