<?php
/**
 * DialectInfoOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Looker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Looker;

/**
 * DialectInfoOptionsTest Class Doc Comment
 *
 * @category    Class */
// * @description DialectInfoOptions
/**
 * @package     Looker
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DialectInfoOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DialectInfoOptions"
     */
    public function testDialectInfoOptions()
    {
    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {
    }

    /**
     * Test attribute "schema"
     */
    public function testPropertySchema()
    {
    }

    /**
     * Test attribute "ssl"
     */
    public function testPropertySsl()
    {
    }

    /**
     * Test attribute "auth"
     */
    public function testPropertyAuth()
    {
    }

    /**
     * Test attribute "host"
     */
    public function testPropertyHost()
    {
    }

    /**
     * Test attribute "tmp_table"
     */
    public function testPropertyTmpTable()
    {
    }

    /**
     * Test attribute "project_name"
     */
    public function testPropertyProjectName()
    {
    }

    /**
     * Test attribute "oauth_credentials"
     */
    public function testPropertyOauthCredentials()
    {
    }

    /**
     * Test attribute "additional_params"
     */
    public function testPropertyAdditionalParams()
    {
    }

    /**
     * Test attribute "username_required"
     */
    public function testPropertyUsernameRequired()
    {
    }

    /**
     * Test attribute "can"
     */
    public function testPropertyCan()
    {
    }
}
