<?php
/**
 * HomepageItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Looker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Looker;

/**
 * HomepageItemTest Class Doc Comment
 *
 * @category    Class */
// * @description HomepageItem
/**
 * @package     Looker
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HomepageItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HomepageItem"
     */
    public function testHomepageItem()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "homepage_section_id"
     */
    public function testPropertyHomepageSectionId()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "custom_title"
     */
    public function testPropertyCustomTitle()
    {
    }

    /**
     * Test attribute "use_custom_title"
     */
    public function testPropertyUseCustomTitle()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "custom_description"
     */
    public function testPropertyCustomDescription()
    {
    }

    /**
     * Test attribute "use_custom_description"
     */
    public function testPropertyUseCustomDescription()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "custom_url"
     */
    public function testPropertyCustomUrl()
    {
    }

    /**
     * Test attribute "use_custom_url"
     */
    public function testPropertyUseCustomUrl()
    {
    }

    /**
     * Test attribute "image_url"
     */
    public function testPropertyImageUrl()
    {
    }

    /**
     * Test attribute "custom_image_url"
     */
    public function testPropertyCustomImageUrl()
    {
    }

    /**
     * Test attribute "custom_image_data_base64"
     */
    public function testPropertyCustomImageDataBase64()
    {
    }

    /**
     * Test attribute "use_custom_image"
     */
    public function testPropertyUseCustomImage()
    {
    }

    /**
     * Test attribute "look_id"
     */
    public function testPropertyLookId()
    {
    }

    /**
     * Test attribute "dashboard_id"
     */
    public function testPropertyDashboardId()
    {
    }

    /**
     * Test attribute "lookml_dashboard_id"
     */
    public function testPropertyLookmlDashboardId()
    {
    }

    /**
     * Test attribute "view_count"
     */
    public function testPropertyViewCount()
    {
    }

    /**
     * Test attribute "favorite_count"
     */
    public function testPropertyFavoriteCount()
    {
    }

    /**
     * Test attribute "content_created_by"
     */
    public function testPropertyContentCreatedBy()
    {
    }

    /**
     * Test attribute "content_updated_at"
     */
    public function testPropertyContentUpdatedAt()
    {
    }

    /**
     * Test attribute "content_favorite_id"
     */
    public function testPropertyContentFavoriteId()
    {
    }

    /**
     * Test attribute "content_metadata_id"
     */
    public function testPropertyContentMetadataId()
    {
    }

    /**
     * Test attribute "section_fetch_time"
     */
    public function testPropertySectionFetchTime()
    {
    }

    /**
     * Test attribute "can"
     */
    public function testPropertyCan()
    {
    }
}
