<?php
/**
 * IntegrationHubTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IntegrationHubTest Class Doc Comment
 *
 * @category    Class */
// * @description IntegrationHub
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IntegrationHubTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IntegrationHub"
     */
    public function testIntegrationHub()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "official"
     */
    public function testPropertyOfficial()
    {
    }

    /**
     * Test attribute "fetch_error_message"
     */
    public function testPropertyFetchErrorMessage()
    {
    }

    /**
     * Test attribute "authorization_token"
     */
    public function testPropertyAuthorizationToken()
    {
    }

    /**
     * Test attribute "has_authorization_token"
     */
    public function testPropertyHasAuthorizationToken()
    {
    }

    /**
     * Test attribute "legal_agreement_signed"
     */
    public function testPropertyLegalAgreementSigned()
    {
    }

    /**
     * Test attribute "legal_agreement_required"
     */
    public function testPropertyLegalAgreementRequired()
    {
    }

    /**
     * Test attribute "legal_agreement_text"
     */
    public function testPropertyLegalAgreementText()
    {
    }

    /**
     * Test attribute "can"
     */
    public function testPropertyCan()
    {
    }
}
