<?php
/**
 * LookmlModelExploreFieldTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Looker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Looker;

/**
 * LookmlModelExploreFieldTest Class Doc Comment
 *
 * @category    Class */
// * @description LookmlModelExploreField
/**
 * @package     Looker
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LookmlModelExploreFieldTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LookmlModelExploreField"
     */
    public function testLookmlModelExploreField()
    {
    }

    /**
     * Test attribute "align"
     */
    public function testPropertyAlign()
    {
    }

    /**
     * Test attribute "can_filter"
     */
    public function testPropertyCanFilter()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "default_filter_value"
     */
    public function testPropertyDefaultFilterValue()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "enumerations"
     */
    public function testPropertyEnumerations()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "field_group_label"
     */
    public function testPropertyFieldGroupLabel()
    {
    }

    /**
     * Test attribute "field_group_variant"
     */
    public function testPropertyFieldGroupVariant()
    {
    }

    /**
     * Test attribute "fill_style"
     */
    public function testPropertyFillStyle()
    {
    }

    /**
     * Test attribute "fiscal_month_offset"
     */
    public function testPropertyFiscalMonthOffset()
    {
    }

    /**
     * Test attribute "has_allowed_values"
     */
    public function testPropertyHasAllowedValues()
    {
    }

    /**
     * Test attribute "hidden"
     */
    public function testPropertyHidden()
    {
    }

    /**
     * Test attribute "is_filter"
     */
    public function testPropertyIsFilter()
    {
    }

    /**
     * Test attribute "is_fiscal"
     */
    public function testPropertyIsFiscal()
    {
    }

    /**
     * Test attribute "is_numeric"
     */
    public function testPropertyIsNumeric()
    {
    }

    /**
     * Test attribute "is_timeframe"
     */
    public function testPropertyIsTimeframe()
    {
    }

    /**
     * Test attribute "can_time_filter"
     */
    public function testPropertyCanTimeFilter()
    {
    }

    /**
     * Test attribute "time_interval"
     */
    public function testPropertyTimeInterval()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "label_from_parameter"
     */
    public function testPropertyLabelFromParameter()
    {
    }

    /**
     * Test attribute "label_short"
     */
    public function testPropertyLabelShort()
    {
    }

    /**
     * Test attribute "lookml_link"
     */
    public function testPropertyLookmlLink()
    {
    }

    /**
     * Test attribute "map_layer"
     */
    public function testPropertyMapLayer()
    {
    }

    /**
     * Test attribute "measure"
     */
    public function testPropertyMeasure()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "parameter"
     */
    public function testPropertyParameter()
    {
    }

    /**
     * Test attribute "permanent"
     */
    public function testPropertyPermanent()
    {
    }

    /**
     * Test attribute "primary_key"
     */
    public function testPropertyPrimaryKey()
    {
    }

    /**
     * Test attribute "project_name"
     */
    public function testPropertyProjectName()
    {
    }

    /**
     * Test attribute "requires_refresh_on_sort"
     */
    public function testPropertyRequiresRefreshOnSort()
    {
    }

    /**
     * Test attribute "scope"
     */
    public function testPropertyScope()
    {
    }

    /**
     * Test attribute "sortable"
     */
    public function testPropertySortable()
    {
    }

    /**
     * Test attribute "source_file"
     */
    public function testPropertySourceFile()
    {
    }

    /**
     * Test attribute "source_file_path"
     */
    public function testPropertySourceFilePath()
    {
    }

    /**
     * Test attribute "sql"
     */
    public function testPropertySql()
    {
    }

    /**
     * Test attribute "sql_case"
     */
    public function testPropertySqlCase()
    {
    }

    /**
     * Test attribute "suggest_dimension"
     */
    public function testPropertySuggestDimension()
    {
    }

    /**
     * Test attribute "suggest_explore"
     */
    public function testPropertySuggestExplore()
    {
    }

    /**
     * Test attribute "suggestable"
     */
    public function testPropertySuggestable()
    {
    }

    /**
     * Test attribute "suggestions"
     */
    public function testPropertySuggestions()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "user_attribute_filter_types"
     */
    public function testPropertyUserAttributeFilterTypes()
    {
    }

    /**
     * Test attribute "value_format"
     */
    public function testPropertyValueFormat()
    {
    }

    /**
     * Test attribute "view"
     */
    public function testPropertyView()
    {
    }

    /**
     * Test attribute "view_label"
     */
    public function testPropertyViewLabel()
    {
    }

    /**
     * Test attribute "dynamic"
     */
    public function testPropertyDynamic()
    {
    }

    /**
     * Test attribute "week_start_day"
     */
    public function testPropertyWeekStartDay()
    {
    }
}
