<?php
/**
 * QueryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QueryTest Class Doc Comment
 *
 * @category    Class */
// * @description Query
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QueryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Query"
     */
    public function testQuery()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "view"
     */
    public function testPropertyView()
    {
    }

    /**
     * Test attribute "fields"
     */
    public function testPropertyFields()
    {
    }

    /**
     * Test attribute "pivots"
     */
    public function testPropertyPivots()
    {
    }

    /**
     * Test attribute "fill_fields"
     */
    public function testPropertyFillFields()
    {
    }

    /**
     * Test attribute "filters"
     */
    public function testPropertyFilters()
    {
    }

    /**
     * Test attribute "filter_expression"
     */
    public function testPropertyFilterExpression()
    {
    }

    /**
     * Test attribute "sorts"
     */
    public function testPropertySorts()
    {
    }

    /**
     * Test attribute "limit"
     */
    public function testPropertyLimit()
    {
    }

    /**
     * Test attribute "column_limit"
     */
    public function testPropertyColumnLimit()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "row_total"
     */
    public function testPropertyRowTotal()
    {
    }

    /**
     * Test attribute "runtime"
     */
    public function testPropertyRuntime()
    {
    }

    /**
     * Test attribute "vis_config"
     */
    public function testPropertyVisConfig()
    {
    }

    /**
     * Test attribute "filter_config"
     */
    public function testPropertyFilterConfig()
    {
    }

    /**
     * Test attribute "visible_ui_sections"
     */
    public function testPropertyVisibleUiSections()
    {
    }

    /**
     * Test attribute "slug"
     */
    public function testPropertySlug()
    {
    }

    /**
     * Test attribute "dynamic_fields"
     */
    public function testPropertyDynamicFields()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "share_url"
     */
    public function testPropertyShareUrl()
    {
    }

    /**
     * Test attribute "expanded_share_url"
     */
    public function testPropertyExpandedShareUrl()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "query_timezone"
     */
    public function testPropertyQueryTimezone()
    {
    }

    /**
     * Test attribute "has_table_calculations"
     */
    public function testPropertyHasTableCalculations()
    {
    }

    /**
     * Test attribute "can"
     */
    public function testPropertyCan()
    {
    }
}
