<?php
/**
 * ScheduledPlanTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Looker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Looker;

/**
 * ScheduledPlanTest Class Doc Comment
 *
 * @category    Class */
// * @description ScheduledPlan
/**
 * @package     Looker
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScheduledPlanTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ScheduledPlan"
     */
    public function testScheduledPlan()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "run_as_recipient"
     */
    public function testPropertyRunAsRecipient()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "next_run_at"
     */
    public function testPropertyNextRunAt()
    {
    }

    /**
     * Test attribute "last_run_at"
     */
    public function testPropertyLastRunAt()
    {
    }

    /**
     * Test attribute "look_id"
     */
    public function testPropertyLookId()
    {
    }

    /**
     * Test attribute "dashboard_id"
     */
    public function testPropertyDashboardId()
    {
    }

    /**
     * Test attribute "lookml_dashboard_id"
     */
    public function testPropertyLookmlDashboardId()
    {
    }

    /**
     * Test attribute "filters_string"
     */
    public function testPropertyFiltersString()
    {
    }

    /**
     * Test attribute "dashboard_filters"
     */
    public function testPropertyDashboardFilters()
    {
    }

    /**
     * Test attribute "require_results"
     */
    public function testPropertyRequireResults()
    {
    }

    /**
     * Test attribute "require_no_results"
     */
    public function testPropertyRequireNoResults()
    {
    }

    /**
     * Test attribute "require_change"
     */
    public function testPropertyRequireChange()
    {
    }

    /**
     * Test attribute "send_all_results"
     */
    public function testPropertySendAllResults()
    {
    }

    /**
     * Test attribute "crontab"
     */
    public function testPropertyCrontab()
    {
    }

    /**
     * Test attribute "datagroup"
     */
    public function testPropertyDatagroup()
    {
    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {
    }

    /**
     * Test attribute "query_id"
     */
    public function testPropertyQueryId()
    {
    }

    /**
     * Test attribute "scheduled_plan_destination"
     */
    public function testPropertyScheduledPlanDestination()
    {
    }

    /**
     * Test attribute "run_once"
     */
    public function testPropertyRunOnce()
    {
    }

    /**
     * Test attribute "include_links"
     */
    public function testPropertyIncludeLinks()
    {
    }

    /**
     * Test attribute "can"
     */
    public function testPropertyCan()
    {
    }
}
