<?php
/**
 * UserTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Looker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Looker;

/**
 * UserTest Class Doc Comment
 *
 * @category    Class */
// * @description User
/**
 * @package     Looker
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "User"
     */
    public function testUser()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "is_disabled"
     */
    public function testPropertyIsDisabled()
    {
    }

    /**
     * Test attribute "avatar_url"
     */
    public function testPropertyAvatarUrl()
    {
    }

    /**
     * Test attribute "home_space_id"
     */
    public function testPropertyHomeSpaceId()
    {
    }

    /**
     * Test attribute "personal_space_id"
     */
    public function testPropertyPersonalSpaceId()
    {
    }

    /**
     * Test attribute "embed_group_space_id"
     */
    public function testPropertyEmbedGroupSpaceId()
    {
    }

    /**
     * Test attribute "access_filters"
     */
    public function testPropertyAccessFilters()
    {
    }

    /**
     * Test attribute "credentials_email"
     */
    public function testPropertyCredentialsEmail()
    {
    }

    /**
     * Test attribute "credentials_totp"
     */
    public function testPropertyCredentialsTotp()
    {
    }

    /**
     * Test attribute "credentials_ldap"
     */
    public function testPropertyCredentialsLdap()
    {
    }

    /**
     * Test attribute "credentials_google"
     */
    public function testPropertyCredentialsGoogle()
    {
    }

    /**
     * Test attribute "credentials_saml"
     */
    public function testPropertyCredentialsSaml()
    {
    }

    /**
     * Test attribute "credentials_oidc"
     */
    public function testPropertyCredentialsOidc()
    {
    }

    /**
     * Test attribute "credentials_api"
     */
    public function testPropertyCredentialsApi()
    {
    }

    /**
     * Test attribute "credentials_api3"
     */
    public function testPropertyCredentialsApi3()
    {
    }

    /**
     * Test attribute "credentials_embed"
     */
    public function testPropertyCredentialsEmbed()
    {
    }

    /**
     * Test attribute "credentials_looker_openid"
     */
    public function testPropertyCredentialsLookerOpenid()
    {
    }

    /**
     * Test attribute "sessions"
     */
    public function testPropertySessions()
    {
    }

    /**
     * Test attribute "role_ids"
     */
    public function testPropertyRoleIds()
    {
    }

    /**
     * Test attribute "group_ids"
     */
    public function testPropertyGroupIds()
    {
    }

    /**
     * Test attribute "presumed_looker_employee"
     */
    public function testPropertyPresumedLookerEmployee()
    {
    }

    /**
     * Test attribute "verified_looker_employee"
     */
    public function testPropertyVerifiedLookerEmployee()
    {
    }

    /**
     * Test attribute "looker_versions"
     */
    public function testPropertyLookerVersions()
    {
    }

    /**
     * Test attribute "ui_state"
     */
    public function testPropertyUiState()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "can"
     */
    public function testPropertyCan()
    {
    }
}
