<?php
/**
 * AuthApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Looker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Looker;

use \Looker\Configuration;
use \Looker\ApiException;
use \Looker\ObjectSerializer;

/**
 * AuthApiTest Class Doc Comment
 *
 * @category Class
 * @package  Looker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AuthApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOidcTestConfig
     *
     * Create OIDC Test Configuration.
     *
     */
    public function testCreateOidcTestConfig()
    {
    }

    /**
     * Test case for createSamlTestConfig
     *
     * Create SAML Test Configuration.
     *
     */
    public function testCreateSamlTestConfig()
    {
    }

    /**
     * Test case for deleteOidcTestConfig
     *
     * Delete OIDC Test Configuration.
     *
     */
    public function testDeleteOidcTestConfig()
    {
    }

    /**
     * Test case for deleteSamlTestConfig
     *
     * Delete SAML Test Configuration.
     *
     */
    public function testDeleteSamlTestConfig()
    {
    }

    /**
     * Test case for fetchAndParseSamlIdpMetadata
     *
     * Parse SAML IdP Url.
     *
     */
    public function testFetchAndParseSamlIdpMetadata()
    {
    }

    /**
     * Test case for ldapConfig
     *
     * Get LDAP Configuration.
     *
     */
    public function testLdapConfig()
    {
    }

    /**
     * Test case for oidcConfig
     *
     * Get OIDC Configuration.
     *
     */
    public function testOidcConfig()
    {
    }

    /**
     * Test case for oidcTestConfig
     *
     * Get OIDC Test Configuration.
     *
     */
    public function testOidcTestConfig()
    {
    }

    /**
     * Test case for parseSamlIdpMetadata
     *
     * Parse SAML IdP XML.
     *
     */
    public function testParseSamlIdpMetadata()
    {
    }

    /**
     * Test case for samlConfig
     *
     * Get SAML Configuration.
     *
     */
    public function testSamlConfig()
    {
    }

    /**
     * Test case for samlTestConfig
     *
     * Get SAML Test Configuration.
     *
     */
    public function testSamlTestConfig()
    {
    }

    /**
     * Test case for testLdapConfigAuth
     *
     * Test LDAP Auth.
     *
     */
    public function testTestLdapConfigAuth()
    {
    }

    /**
     * Test case for testLdapConfigConnection
     *
     * Test LDAP Connection.
     *
     */
    public function testTestLdapConfigConnection()
    {
    }

    /**
     * Test case for testLdapConfigUserAuth
     *
     * Test LDAP User Auth.
     *
     */
    public function testTestLdapConfigUserAuth()
    {
    }

    /**
     * Test case for testLdapConfigUserInfo
     *
     * Test LDAP User Info.
     *
     */
    public function testTestLdapConfigUserInfo()
    {
    }

    /**
     * Test case for updateLdapConfig
     *
     * Update LDAP Configuration.
     *
     */
    public function testUpdateLdapConfig()
    {
    }

    /**
     * Test case for updateOidcConfig
     *
     * Update OIDC Configuration.
     *
     */
    public function testUpdateOidcConfig()
    {
    }

    /**
     * Test case for updateSamlConfig
     *
     * Update SAML Configuration.
     *
     */
    public function testUpdateSamlConfig()
    {
    }
}
