<?php
/**
 * ConnectionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Looker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Looker;

use \Looker\Configuration;
use \Looker\ApiException;
use \Looker\ObjectSerializer;

/**
 * ConnectionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Looker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConnectionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for allConnections
     *
     * Get All Connections.
     *
     */
    public function testAllConnections()
    {
    }

    /**
     * Test case for allDialectInfos
     *
     * Get All Dialect Infos.
     *
     */
    public function testAllDialectInfos()
    {
    }

    /**
     * Test case for connection
     *
     * Get Connection.
     *
     */
    public function testConnection()
    {
    }

    /**
     * Test case for createConnection
     *
     * Create Connection.
     *
     */
    public function testCreateConnection()
    {
    }

    /**
     * Test case for deleteConnection
     *
     * Delete Connection.
     *
     */
    public function testDeleteConnection()
    {
    }

    /**
     * Test case for deleteConnectionOverride
     *
     * Delete Connection.
     *
     */
    public function testDeleteConnectionOverride()
    {
    }

    /**
     * Test case for testConnection
     *
     * Test Connection.
     *
     */
    public function testTestConnection()
    {
    }

    /**
     * Test case for testConnectionConfig
     *
     * Test Connection Configuration.
     *
     */
    public function testTestConnectionConfig()
    {
    }

    /**
     * Test case for updateConnection
     *
     * Update Connection.
     *
     */
    public function testUpdateConnection()
    {
    }
}
