<?php
/**
 * GroupApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * GroupApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GroupApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addGroupGroup
     *
     * Add a Group to Group.
     *
     */
    public function testAddGroupGroup()
    {
    }

    /**
     * Test case for addGroupUser
     *
     * Add a User to Group.
     *
     */
    public function testAddGroupUser()
    {
    }

    /**
     * Test case for allGroupGroups
     *
     * Get All Groups in Group.
     *
     */
    public function testAllGroupGroups()
    {
    }

    /**
     * Test case for allGroupUsers
     *
     * Get All Users in Group.
     *
     */
    public function testAllGroupUsers()
    {
    }

    /**
     * Test case for allGroups
     *
     * Get All Groups.
     *
     */
    public function testAllGroups()
    {
    }

    /**
     * Test case for createGroup
     *
     * Create Group.
     *
     */
    public function testCreateGroup()
    {
    }

    /**
     * Test case for deleteGroup
     *
     * Delete Group.
     *
     */
    public function testDeleteGroup()
    {
    }

    /**
     * Test case for deleteGroupFromGroup
     *
     * Deletes a Group from Group.
     *
     */
    public function testDeleteGroupFromGroup()
    {
    }

    /**
     * Test case for deleteGroupUser
     *
     * Remove a User from Group.
     *
     */
    public function testDeleteGroupUser()
    {
    }

    /**
     * Test case for deleteUserAttributeGroupValue
     *
     * Delete User Attribute Group Value.
     *
     */
    public function testDeleteUserAttributeGroupValue()
    {
    }

    /**
     * Test case for group
     *
     * Get Group.
     *
     */
    public function testGroup()
    {
    }

    /**
     * Test case for updateGroup
     *
     * Update Group.
     *
     */
    public function testUpdateGroup()
    {
    }

    /**
     * Test case for updateUserAttributeGroupValue
     *
     * Set User Attribute Group Value.
     *
     */
    public function testUpdateUserAttributeGroupValue()
    {
    }
}
