<?php
/**
 * IntegrationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Looker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Experimental Looker API 3.1 Preview
 *
 * This API 3.1 is in active development. Breaking changes are likely to occur to some API functions in future Looker releases until API 3.1 is officially launched and upgraded to beta status.  If you have time and interest to experiment with new or modified services exposed in this embryonic API 3.1, we welcome your participation and feedback!  For large development efforts or critical line-of-business projects, we strongly recommend you stick with the API 3.0 while API 3.1 is under construction.
 *
 * OpenAPI spec version: 3.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Looker;

use \Looker\Configuration;
use \Looker\ApiException;
use \Looker\ObjectSerializer;

/**
 * IntegrationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Looker
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IntegrationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for acceptIntegrationHubLegalAgreement
     *
     * Accept Integration Hub Legal Agreement.
     *
     */
    public function testAcceptIntegrationHubLegalAgreement()
    {
    }

    /**
     * Test case for allIntegrationHubs
     *
     * Get All Integration Hubs.
     *
     */
    public function testAllIntegrationHubs()
    {
    }

    /**
     * Test case for allIntegrations
     *
     * Get All Integrations.
     *
     */
    public function testAllIntegrations()
    {
    }

    /**
     * Test case for createIntegrationHub
     *
     * Create Integration Hub.
     *
     */
    public function testCreateIntegrationHub()
    {
    }

    /**
     * Test case for deleteIntegrationHub
     *
     * Delete Integration Hub.
     *
     */
    public function testDeleteIntegrationHub()
    {
    }

    /**
     * Test case for fetchIntegrationForm
     *
     * Fetch Remote Integration Form.
     *
     */
    public function testFetchIntegrationForm()
    {
    }

    /**
     * Test case for integration
     *
     * Get Integration.
     *
     */
    public function testIntegration()
    {
    }

    /**
     * Test case for integrationHub
     *
     * Get Integration Hub.
     *
     */
    public function testIntegrationHub()
    {
    }

    /**
     * Test case for updateIntegration
     *
     * Update Integration.
     *
     */
    public function testUpdateIntegration()
    {
    }

    /**
     * Test case for updateIntegrationHub
     *
     * Update Integration Hub.
     *
     */
    public function testUpdateIntegrationHub()
    {
    }
}
